/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnswerUpdateManyWithoutSurveysInput } from "./AnswerUpdateManyWithoutSurveysInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { DrawingWhereUniqueInput } from "../../drawing/base/DrawingWhereUniqueInput";
import { QuestionUpdateManyWithoutSurveysInput } from "./QuestionUpdateManyWithoutSurveysInput";
import { ResearcherWhereUniqueInput } from "../../researcher/base/ResearcherWhereUniqueInput";
@InputType()
class SurveyUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AnswerUpdateManyWithoutSurveysInput,
  })
  @ValidateNested()
  @Type(() => AnswerUpdateManyWithoutSurveysInput)
  @IsOptional()
  @Field(() => AnswerUpdateManyWithoutSurveysInput, {
    nullable: true,
  })
  answers?: AnswerUpdateManyWithoutSurveysInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => DrawingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DrawingWhereUniqueInput)
  @IsOptional()
  @Field(() => DrawingWhereUniqueInput, {
    nullable: true,
  })
  drawingId?: DrawingWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numOfQuestions?: number;

  @ApiProperty({
    required: false,
    type: () => QuestionUpdateManyWithoutSurveysInput,
  })
  @ValidateNested()
  @Type(() => QuestionUpdateManyWithoutSurveysInput)
  @IsOptional()
  @Field(() => QuestionUpdateManyWithoutSurveysInput, {
    nullable: true,
  })
  questions?: QuestionUpdateManyWithoutSurveysInput;

  @ApiProperty({
    required: false,
    type: () => ResearcherWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResearcherWhereUniqueInput)
  @IsOptional()
  @Field(() => ResearcherWhereUniqueInput, {
    nullable: true,
  })
  researcherId?: ResearcherWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;
}
export { SurveyUpdateInput };
