/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSurveyArgs } from "./CreateSurveyArgs";
import { UpdateSurveyArgs } from "./UpdateSurveyArgs";
import { DeleteSurveyArgs } from "./DeleteSurveyArgs";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyFindUniqueArgs } from "./SurveyFindUniqueArgs";
import { Survey } from "./Survey";
import { AnswerFindManyArgs } from "../../answer/base/AnswerFindManyArgs";
import { Answer } from "../../answer/base/Answer";
import { QuestionFindManyArgs } from "../../question/base/QuestionFindManyArgs";
import { Question } from "../../question/base/Question";
import { Drawing } from "../../drawing/base/Drawing";
import { Researcher } from "../../researcher/base/Researcher";
import { SurveyService } from "../survey.service";

@graphql.Resolver(() => Survey)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SurveyResolverBase {
  constructor(
    protected readonly service: SurveyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "any",
  })
  async _surveysMeta(
    @graphql.Args() args: SurveyFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Survey])
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "any",
  })
  async surveys(@graphql.Args() args: SurveyFindManyArgs): Promise<Survey[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Survey, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "read",
    possession: "own",
  })
  async survey(
    @graphql.Args() args: SurveyFindUniqueArgs
  ): Promise<Survey | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "create",
    possession: "any",
  })
  async createSurvey(@graphql.Args() args: CreateSurveyArgs): Promise<Survey> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        drawingId: args.data.drawingId
          ? {
              connect: args.data.drawingId,
            }
          : undefined,

        researcherId: args.data.researcherId
          ? {
              connect: args.data.researcherId,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "update",
    possession: "any",
  })
  async updateSurvey(
    @graphql.Args() args: UpdateSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          drawingId: args.data.drawingId
            ? {
                connect: args.data.drawingId,
              }
            : undefined,

          researcherId: args.data.researcherId
            ? {
                connect: args.data.researcherId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Survey)
  @nestAccessControl.UseRoles({
    resource: "Survey",
    action: "delete",
    possession: "any",
  })
  async deleteSurvey(
    @graphql.Args() args: DeleteSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Answer])
  @nestAccessControl.UseRoles({
    resource: "Answer",
    action: "read",
    possession: "any",
  })
  async answers(
    @graphql.Parent() parent: Survey,
    @graphql.Args() args: AnswerFindManyArgs
  ): Promise<Answer[]> {
    const results = await this.service.findAnswers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Question])
  @nestAccessControl.UseRoles({
    resource: "Question",
    action: "read",
    possession: "any",
  })
  async questions(
    @graphql.Parent() parent: Survey,
    @graphql.Args() args: QuestionFindManyArgs
  ): Promise<Question[]> {
    const results = await this.service.findQuestions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Drawing, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Drawing",
    action: "read",
    possession: "any",
  })
  async drawingId(@graphql.Parent() parent: Survey): Promise<Drawing | null> {
    const result = await this.service.getDrawingId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Researcher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Researcher",
    action: "read",
    possession: "any",
  })
  async researcherId(
    @graphql.Parent() parent: Survey
  ): Promise<Researcher | null> {
    const result = await this.service.getResearcherId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
