/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ChildService } from "../child.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ChildCreateInput } from "./ChildCreateInput";
import { ChildWhereInput } from "./ChildWhereInput";
import { ChildWhereUniqueInput } from "./ChildWhereUniqueInput";
import { ChildFindManyArgs } from "./ChildFindManyArgs";
import { ChildUpdateInput } from "./ChildUpdateInput";
import { Child } from "./Child";
import { AnswerFindManyArgs } from "../../answer/base/AnswerFindManyArgs";
import { Answer } from "../../answer/base/Answer";
import { AnswerWhereUniqueInput } from "../../answer/base/AnswerWhereUniqueInput";
import { DrawingFindManyArgs } from "../../drawing/base/DrawingFindManyArgs";
import { Drawing } from "../../drawing/base/Drawing";
import { DrawingWhereUniqueInput } from "../../drawing/base/DrawingWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ChildControllerBase {
  constructor(
    protected readonly service: ChildService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Child })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ChildCreateInput): Promise<Child> {
    return await this.service.create({
      data: data,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        nationality: true,
        phoneNumber: true,
        smsCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Child] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ChildFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Child[]> {
    const args = plainToClass(ChildFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        nationality: true,
        phoneNumber: true,
        smsCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Child | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        nationality: true,
        phoneNumber: true,
        smsCode: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() data: ChildUpdateInput
  ): Promise<Child | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          gender: true,
          id: true,
          nationality: true,
          phoneNumber: true,
          smsCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Child | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          age: true,
          createdAt: true,
          gender: true,
          id: true,
          nationality: true,
          phoneNumber: true,
          smsCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Answer",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/answers")
  @ApiNestedQuery(AnswerFindManyArgs)
  async findManyAnswers(
    @common.Req() request: Request,
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Answer[]> {
    const query = plainToClass(AnswerFindManyArgs, request.query);
    const results = await this.service.findAnswers(params.id, {
      ...query,
      select: {
        childId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        questionId: {
          select: {
            id: true,
          },
        },

        surveyId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/answers")
  async connectAnswers(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      answers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/answers")
  async updateAnswers(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      answers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/answers")
  async disconnectAnswers(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: AnswerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      answers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Drawing",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/drawings")
  @ApiNestedQuery(DrawingFindManyArgs)
  async findManyDrawings(
    @common.Req() request: Request,
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Drawing[]> {
    const query = plainToClass(DrawingFindManyArgs, request.query);
    const results = await this.service.findDrawings(params.id, {
      ...query,
      select: {
        childId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fileAddress: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/drawings")
  async connectDrawings(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: DrawingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      drawings: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/drawings")
  async updateDrawings(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: DrawingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      drawings: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/drawings")
  async disconnectDrawings(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: DrawingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      drawings: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
